setwd("C:/Users/Abzooba/Documents/UCI HAR Dataset/test")
test_sub<-read.table("subject_test.txt",sep=" ")
test_lab<-read.table("y_test.txt",sep=" ")
test_X<-read.table("X_test.txt",sep="")
names(test_sub)=c("subject")
names(test_lab)=c("activity")
test<-cbind.data.frame(test_X,test_sub,test_lab,stringsAsFactors=FALSE)
setwd("C:/Users/Abzooba/Documents/UCI HAR Dataset/train")
train_sub<-read.table("subject_train.txt",sep=" ")
train_lab<-read.table("y_train.txt",sep=" ")
train_X<-read.table("X_train.txt",sep="")
names(train_sub)=c("subject")
names(train_lab)=c("activity")
train<-cbind.data.frame(train_X,train_sub,train_lab,stringsAsFactors=FALSE)
data<-rbind.data.frame(train,test)
setwd("C:/Users/Abzooba/Documents/UCI HAR Dataset")
labels<-read.table("features.txt",sep=" ",stringsAsFactors=FALSE)
mn<-grep("mean",labels[,2])
sd<-grep("std",labels[,2])
mes<-c(mn,sd,562,563)
mes1<-c(mn,sd)
mes<-sort(mes)
data<-data[,mes]
mes1<-sort(mes1)
col<-labels[mes1,2]
names(data)[1:79]<-col
data[,"activity"]<-as.factor(data[,"activity"])
levels(data[,"activity"])<-c("WALKING","WALKING_UPSTAIRS","WALKING_DOWNSTAIRS","SITTING","STANDING","LAYING")
library("dplyr")
data1<-data %>% group_by(activity,subject) %>% summarise_each(funs(mean))
write.table(data1,"data.txt",sep=" ",row.names=FALSE)
